Check if files exist before sourcing

diff --git a/bin/bavice b/bin/bavice
--- a/bin/bavice
+++ b/bin/bavice
@@ -13,10 +13,20 @@ exec 1> >(logger -t "$SCRIPT_NAME") 2>&1
 function pre_backup() { :; }
 function post_backup() { :; }
 
-# shellcheck source=/dev/null
-source "$CONFIG_PATH/env.sh"
-# shellcheck source=/dev/null
-source "$CONFIG_PATH/hooks.sh"
+if [[ -f "$CONFIG_PATH/env.sh" ]]; then
+	printf "%s\n" 'Sourcing local environment.'
+	# shellcheck source=/dev/null
+	source "$CONFIG_PATH/env.sh"
+else
+	printf "%s\n" 'Cannot source local environment.'
+	exit 1
+fi
+
+if [[ -f "$CONFIG_PATH/hooks.sh" ]]; then
+	printf "%s\n" 'Sourcing local hooks.'
+	# shellcheck source=/dev/null
+	source "$CONFIG_PATH/hooks.sh"
+fi
 
 if [ -z "$PUSHBITS_HOSTNAME" ]; then
 	printf "%s\n" 'No hostname for PushBits instance was supplied!'
